currentRoot: http://www.trustees.uillinois.edu/trustees/resources/
downloadRoot: http://www.trustees.uillinois.edu/trustees/resources/historical-files/
start: 2007
end: 2021
employeeCodes:
  AA: true
  AB: true
  AG: true
  AH: true
  AL: true
  AM: true
  BA: true
  BB: true
  BC: true
  BD: true
  BG: true
  BH: true
  PA: true
  PB: true
tenureCodes:
  A: true
  M: true
  N: true
  P: true
  Q: true
  T: true
  W: true
categoryMapping:
  AE:
    name: Admin Info Technology Services
    location: System Offices
  AH:
    name: Exec VP & VP Academic Affairs
    location: System Offices
  AA:
    name: Executive Offices
    location: System Offices
  AF:
    name: Ofc of Procurement Services
    location: System Offices
  AU:
    name: Office of Business Services
    location: System Offices
  AR:
    name: Office of Treasury Operations
    location: System Offices
  AS:
    name: Office of the Controller
    location: System Offices
  AM:
    name: UIF and UIAA
    location: System Offices
  AD:
    name: University Audits
    location: System Offices
  AN:
    name: University Ethics Office
    location: System Offices
  AP:
    name: VP Chief Financial Officer
    location: System Offices
  AJ:
    name: Vice Pres Econ Dev and Innov
    location: System Offices
  AT:
    name: Vice Pres External Rel & Comm
    location: System Offices
  SC:
    name: Administrative Affairs
    location: Springfield University
  SJ:
    name: Advancement
    location: Springfield University
  SG:
    name: Auxiliary Units
    location: Springfield University
  PE:
    name: Business and Management
    location: Springfield University
  PL:
    name: Center for State Policy
    location: Springfield University
  SA:
    name: Chancellor
    location: Springfield University
  SH:
    name: Division of Finance & Admin
    location: Springfield University
  PD:
    name: Health, Science, and Technology
    location: Springfield University
  PH:
    name: Liberal Arts & Sciences
    location: Springfield University
  SB:
    name: Provost & VC Acad Affairs
    location: Springfield University
  PF:
    name: Public Affairs & Administratn
    location: Springfield University
  SE:
    name: Student Affairs
    location: Springfield University
  PK:
    name: University Library
    location: Springfield University
  GF:
    name: Applied Health Sciences
    location: Chicago University
  FR:
    name: Architecture,Design,& the Arts
    location: Chicago University
  FL:
    name: Business Administration
    location: Chicago University
  JP:
    name: Campus Auxiliary Services
    location: Chicago University
  JA:
    name: Chancellor
    location: Chicago University
  FZ:
    name: Coll Medicine at Chicago - BS
    location: Chicago University
  GA:
    name: Coll Medicine at Chicago - CS
    location: Chicago University
  FV:
    name: Coll of Med Office of the Dean
    location: Chicago University
  GE:
    name: College of Medicine Rockford
    location: Chicago University
  GC:
    name: College of Medicine at Peoria
    location: Chicago University
  GS:
    name: Community Health
    location: Chicago University
  FN:
    name: Dentistry
    location: Chicago University
  FM:
    name: Div of Specializ Care for Chil
    location: Chicago University
  FP:
    name: Education
    location: Chicago University
  FQ:
    name: Engineering
    location: Chicago University
  FS:
    name: Graduate College
    location: Chicago University
  JD:
    name: Healthcare System, UIC-MSHC
    location: Chicago University
  GH:
    name: Healthcare Systems, UIC - MC
    location: Chicago University
  GT:
    name: Honors College
    location: Chicago University
  HD:
    name: Innovation Center
    location: Chicago University
  JT:
    name: Intercollegiate Athletics
    location: Chicago University
  FT:
    name: Liberal Arts & Sciences
    location: Chicago University
  GQ:
    name: Library
    location: Chicago University
  FW:
    name: Nursing
    location: Chicago University
  JQ:
    name: Office for Access and Equity
    location: Chicago University
  JS:
    name: Office of VC for Advancement
    location: Chicago University
  FX:
    name: Pharmacy
    location: Chicago University
  JB:
    name: Provost & VC Acad Affairs
    location: Chicago University
  FY:
    name: School of Public Health
    location: Chicago University
  HC:
    name: Social Justice Initiative
    location: Chicago University
  GL:
    name: Social Work
    location: Chicago University
  JU:
    name: Strategic Mktg & Comm
    location: Chicago University
  JK:
    name: Student Affairs Ancillary Svcs
    location: Chicago University
  JV:
    name: Technology Solutions
    location: Chicago University
  FH:
    name: UI Cancer Center
    location: Chicago University
  GN:
    name: UIC Extended Campus
    location: Chicago University
  FJ:
    name: UIC School of Law
    location: Chicago University
  GP:
    name: Urban Planning &Public Affairs
    location: Chicago University
  HY:
    name: Utilities Administration-UIC
    location: Chicago University
  JY:
    name: VC Budget HR & Financial Admin
    location: Chicago University
  JW:
    name: VC for Health Affairs
    location: Chicago University
  JE:
    name: VP Academic & Enrollment Svcs
    location: Chicago University
  HB:
    name: VP Undrgrd Affrs & Acdmc Prgms
    location: Chicago University
  JX:
    name: VP for Global Engagement
    location: Chicago University
  JC:
    name: Vice Chanc Administrative Svcs
    location: Chicago University
  JR:
    name: Vice Chanc Diversity Equ Eng
    location: Chicago University
  JJ:
    name: Vice Chanc for Student Affairs
    location: Chicago University
  JZ:
    name: Vice Chancellor for Innovation
    location: Chicago University
  JF:
    name: Vice Chancellor for Research
    location: Chicago University
  HE:
    name: Vice Provost Faculty Affairs
    location: Chicago University
  KL:
    name: Agr, Consumer & Env Sciences
    location: Urbana-Champaign University
  KY:
    name: Applied Health Sciences
    location: Urbana-Champaign University
  LD:
    name: Armed Forces
    location: Urbana-Champaign University
  NQ:
    name: Auxiliary Units
    location: Urbana-Champaign University
  LT:
    name: Carle Illinois Medicine
    location: Urbana-Champaign University
  LN:
    name: Center Innov in Teach Learn
    location: Urbana-Champaign University
  NA:
    name: Chancellor
    location: Urbana-Champaign University
  KT:
    name: College of Media
    location: Urbana-Champaign University
  NU:
    name: Div Intercollegiate Athletics
    location: Urbana-Champaign University
  KW:
    name: Division of General Studies
    location: Urbana-Champaign University
  KN:
    name: Education
    location: Urbana-Champaign University
  MY:
    name: Energy Services
    location: Urbana-Champaign University
  NN:
    name: Facilities
    location: Urbana-Champaign University
  KR:
    name: Fine & Applied Arts
    location: Urbana-Champaign University
  KM:
    name: Gies College of Business
    location: Urbana-Champaign University
  KS:
    name: Graduate College
    location: Urbana-Champaign University
  KP:
    name: Grainger Engineering
    location: Urbana-Champaign University
  LQ:
    name: Illinois International
    location: Urbana-Champaign University
  KU:
    name: Law
    location: Urbana-Champaign University
  KV:
    name: Liberal Arts & Sciences
    location: Urbana-Champaign University
  LB:
    name: Medicine at UIUC
    location: Urbana-Champaign University
  NP:
    name: OVCRI Institutes
    location: Urbana-Champaign University
  NS:
    name: Ofc VC Inst Advancement
    location: Urbana-Champaign University
  NB:
    name: Provost & VC Acad Affairs
    location: Urbana-Champaign University
  LF:
    name: Public Safety
    location: Urbana-Champaign University
  LP:
    name: School of Information Sciences
    location: Urbana-Champaign University
  LG:
    name: School of Labor & Empl. Rel.
    location: Urbana-Champaign University
  LL:
    name: School of Social Work
    location: Urbana-Champaign University
  NT:
    name: Technology Services
    location: Urbana-Champaign University
  LR:
    name: University Library
    location: Urbana-Champaign University
  NL:
    name: VC Admin and Operations
    location: Urbana-Champaign University
  NJ:
    name: VC Student Affairs
    location: Urbana-Champaign University
  NE:
    name: VC for Research and Innovation
    location: Urbana-Champaign University
  LC:
    name: Veterinary Medicine
    location: Urbana-Champaign University
  NV:
    name: Vice Chancellor for Diversity
    location: Urbana-Champaign University
knownTitles:
  - Asst Var Coach Mens Baseball
  - Resource & Policy Analyst
  - Bus Srvs Spec
  - Sponsored Projects Specialist
  - Acad Advisor/Online Coord
  - Archival Operations & Ref Spec
  - "Coord of Int'l Projects"
  - Plan Review Coord
  - Coord of Business Operations
  - Systems Engineer
  - Dir of Dept Bus Affairs
  - Technol Spec
  - BH PROF & DIR IN RESIDENCE
  - Senior Application Specialist
  - Engineer, Capital Planning
  - Research Project Manager
  - Clinical Counselor
  - Asst Director, HR-College
  - Clinical Assistant Professor
  - Res Data Analyst
  - Asst Prof
  - Exec Dir for Univ Payroll
  - Enterprise-Wide Auditor
  - Sr Fellow
  - Clin Assoc Prof of Pham in Med
  - Clinical Pharmacist
  - Coordinator Grants & Contracts
  - Parent Program Specialist
  - Advanced Practice Nurse
  - Professor
  - Asst Dir of Hosp Fin Budg & Ca
  - Manager, Nursing Admin. Svcs
  - Head Women Soccer Coach
  - Director of Web Services
  - Assoc Dir Conf Serv
  - Dir Conf Services
  - Systems Integrator
  - Project Manager
  - AG & CASH MGMT ANALYST
  - CHANC UIC & VPRES UI
  - CZECH/SLOVAK LGL EXCH DIR
  - DIR, INATL STDNT PRGM
  - Head, Professional Pilot Div
  - Assoc Dir Creative Writing
  - Acting Airport Manager
  - Dir Ofc Rsk Mgt & Ins Res
  - Dir Undergrad Studies
  - Fire College Coordinator
  - "Asst Head Curr&Instr"
  - "Sen Assoc VP Bus & Finance"
